//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArzExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArzExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract.
        /// </summary>
        internal static string ARZExtractBtnExtract {
            get {
                return ResourceManager.GetString("ARZExtractBtnExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist.  Would you like to create it now?.
        /// </summary>
        internal static string ARZExtractCreateFolder {
            get {
                return ResourceManager.GetString("ARZExtractCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create folder?.
        /// </summary>
        internal static string ARZExtractCreateFolder2 {
            get {
                return ResourceManager.GetString("ARZExtractCreateFolder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist for IT database.  Would you like to create it now?.
        /// </summary>
        internal static string ARZExtractCreateFolderIT {
            get {
                return ResourceManager.GetString("ARZExtractCreateFolderIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the destination folder for the extracted database records.
        /// </summary>
        internal static string ARZExtractDestination {
            get {
                return ResourceManager.GetString("ARZExtractDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a folder, not a file!.
        /// </summary>
        internal static string ARZExtractFileDest {
            get {
                return ResourceManager.GetString("ARZExtractFileDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently there is no way to extract all of the game database records at once.  Also there currently exists a bug in the Toolset that destroys array values when you extract records one by one.  Using this tool, you can now extract all records at once and all the records will be extracted correctly..
        /// </summary>
        internal static string ARZExtractLabel1 {
            get {
                return ResourceManager.GetString("ARZExtractLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After you have extracted the records, just copy the ones you want to use in your mod over to your mod folder..
        /// </summary>
        internal static string ARZExtractLabel2 {
            get {
                return ResourceManager.GetString("ARZExtractLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a destination folder:.
        /// </summary>
        internal static string ARZExtractLabel3 {
            get {
                return ResourceManager.GetString("ARZExtractLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a destination folder for IT Database Files:.
        /// </summary>
        internal static string ARZExtractLabel4 {
            get {
                return ResourceManager.GetString("ARZExtractLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If not populated the destination folders for the TQ database and the IT database will default to the same folder.  The IT files will overwrite the TQ files when there are conflicts though you can select different folders to avoid overwriting files..
        /// </summary>
        internal static string ARZExtractLabel5 {
            get {
                return ResourceManager.GetString("ARZExtractLabel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract database.arz.
        /// </summary>
        internal static string ARZExtractText {
            get {
                return ResourceManager.GetString("ARZExtractText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a valid destination folder..
        /// </summary>
        internal static string ARZExtractValidDest {
            get {
                return ResourceManager.GetString("ARZExtractValidDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction cancelled..
        /// </summary>
        internal static string ARZProgressCancelledText {
            get {
                return ResourceManager.GetString("ARZProgressCancelledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction complete..
        /// </summary>
        internal static string ARZProgressCompleteText {
            get {
                return ResourceManager.GetString("ARZProgressCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction Failed..
        /// </summary>
        internal static string ARZProgressFailedText {
            get {
                return ResourceManager.GetString("ARZProgressFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting {0} ....
        /// </summary>
        internal static string ARZProgressLabel {
            get {
                return ResourceManager.GetString("ARZProgressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting.
        /// </summary>
        internal static string ARZProgressLabel1 {
            get {
                return ResourceManager.GetString("ARZProgressLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting database.arz....
        /// </summary>
        internal static string ARZProgressText {
            get {
                return ResourceManager.GetString("ARZProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon CapsDown {
            get {
                object obj = ResourceManager.GetObject("CapsDown", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon CapsUP {
            get {
                object obj = ResourceManager.GetObject("CapsUP", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ClearHistory {
            get {
                object obj = ResourceManager.GetObject("ClearHistory", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string GlobalCancel {
            get {
                return ResourceManager.GetString("GlobalCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon LoadDatabase {
            get {
                object obj = ResourceManager.GetObject("LoadDatabase", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Next {
            get {
                object obj = ResourceManager.GetObject("Next", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Prev {
            get {
                object obj = ResourceManager.GetObject("Prev", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
