//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArzExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArzExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extract.
        /// </summary>
        internal static string ARZExtractBtnExtract {
            get {
                return ResourceManager.GetString("ARZExtractBtnExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} does not exist.  Would you like to create it now?.
        /// </summary>
        internal static string ARZExtractCreateFolder {
            get {
                return ResourceManager.GetString("ARZExtractCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create folder?.
        /// </summary>
        internal static string ARZExtractCreateFolder2 {
            get {
                return ResourceManager.GetString("ARZExtractCreateFolder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} does not exist for IT database.  Would you like to create it now?.
        /// </summary>
        internal static string ARZExtractCreateFolderIT {
            get {
                return ResourceManager.GetString("ARZExtractCreateFolderIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the destination folder for the extracted database records.
        /// </summary>
        internal static string ARZExtractDestination {
            get {
                return ResourceManager.GetString("ARZExtractDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must specify a folder, not a file!.
        /// </summary>
        internal static string ARZExtractFileDest {
            get {
                return ResourceManager.GetString("ARZExtractFileDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Currently there is no way to extract all of the game database records at once.  Also there currently exists a bug in the Toolset that destroys array values when you extract records one by one.  Using this tool, you can now extract all records at once and all the records will be extracted correctly..
        /// </summary>
        internal static string ARZExtractLabel1 {
            get {
                return ResourceManager.GetString("ARZExtractLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à After you have extracted the records, just copy the ones you want to use in your mod over to your mod folder..
        /// </summary>
        internal static string ARZExtractLabel2 {
            get {
                return ResourceManager.GetString("ARZExtractLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a destination folder:.
        /// </summary>
        internal static string ARZExtractLabel3 {
            get {
                return ResourceManager.GetString("ARZExtractLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a destination folder for IT Database Files:.
        /// </summary>
        internal static string ARZExtractLabel4 {
            get {
                return ResourceManager.GetString("ARZExtractLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If not populated the destination folders for the TQ database and the IT database will default to the same folder.  The IT files will overwrite the TQ files when there are conflicts though you can select different folders to avoid overwriting files..
        /// </summary>
        internal static string ARZExtractLabel5 {
            get {
                return ResourceManager.GetString("ARZExtractLabel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extract database.arz.
        /// </summary>
        internal static string ARZExtractText {
            get {
                return ResourceManager.GetString("ARZExtractText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must enter a valid destination folder..
        /// </summary>
        internal static string ARZExtractValidDest {
            get {
                return ResourceManager.GetString("ARZExtractValidDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extraction cancelled..
        /// </summary>
        internal static string ARZProgressCancelledText {
            get {
                return ResourceManager.GetString("ARZProgressCancelledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extraction complete..
        /// </summary>
        internal static string ARZProgressCompleteText {
            get {
                return ResourceManager.GetString("ARZProgressCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extraction Failed..
        /// </summary>
        internal static string ARZProgressFailedText {
            get {
                return ResourceManager.GetString("ARZProgressFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extracting {0} ....
        /// </summary>
        internal static string ARZProgressLabel {
            get {
                return ResourceManager.GetString("ARZProgressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extracting.
        /// </summary>
        internal static string ARZProgressLabel1 {
            get {
                return ResourceManager.GetString("ARZProgressLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extracting database.arz....
        /// </summary>
        internal static string ARZProgressText {
            get {
                return ResourceManager.GetString("ARZProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string GlobalCancel {
            get {
                return ResourceManager.GetString("GlobalCancel", resourceCulture);
            }
        }
    }
}
